version: '3'

services:
  foody_app:
    build: ./config/docker
    container_name: app_foody
    environment:
      #- NODE_ENV=production
      - LOCAL_USER_ID=$USER_ID
      - LOCAL_GROUP_ID=$GROUP_ID
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - VIRTUAL_HOST=foody.${SITE_URL}
      - VIRTUAL_PORT=3339
      - LETSENCRYPT_HOST=foody.${SITE_URL},api-foody.${SITE_URL}
      - LETSENCRYPT_EMAIL=${MAILER_DEFAUT_SENDER_ADDRESS}
    depends_on:
      - foody_api
    ports:
      - 3339:3000
    volumes:
      - .:/app

  foody_api:
    build: ./config/docker
    container_name: api_foody
    environment:
      #- NODE_ENV=production
      - LOCAL_USER_ID=$USER_ID
      - LOCAL_GROUP_ID=$GROUP_ID
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - VIRTUAL_HOST=api-foody.${SITE_URL}                      
      - VIRTUAL_PORT=3340
      - LETSENCRYPT_HOST=api-foody.${SITE_URL},api-foody.${SITE_URL}
      - LETSENCRYPT_EMAIL=${MAILER_DEFAUT_SENDER_ADDRESS}
    ports:
      - 3340:1337
    volumes:
      - .:/app


networks:
  default:
    external:
      name: nginx-proxy
